spring:
  application:
    name: api-gateway
server:
  port: 8085
  address: 0.0.0.0
jwt:
  header: Authorization
  secret: BPharmaSecret@12
  expiration: 604800
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG